# 违禁Mod列表
banned-mods:
  - "cheatmod"
  - "hackmod"
  - "xray"
  - "wurst"
  - "wurstclient"
  - "comet"
  - "cometclient"
  - "aristois"
  - "aristoisclient"
  - "impact"
  - "impactclient"
  - "meteor"
  - "meteorclient"
  - "bleachhack"
  - "bleachhackclient"
  - "future"
  - "futureclient"
  - "kami"
  - "kamiblue"
  - "kamiblueclient"
  - "lambda"
  - "lambdaclient"
  - "rusherhack"
  - "rusherhackclient"
  - "sigma"
  - "sigmaclient"
  - "phobos"
  - "phobosclient"
  - "konas"
  - "konasclient"
  - "pyro"
  - "pyroclient"
  - "seppuku"
  - "seppukuclient"
  - "salhack"
  - "salhackclient"
  - "gamesense"
  - "gamesenseclient"
  - "wolfram"
  - "wolframclient"
  - "zero"
  - "zeroclient"
  - "liquidbounce"
  - "liquidbounceclient"
  - "fdpclient"
  - "fdp"

# 管理员列表
staff:
  - "AdminPlayer1"
  - "AdminPlayer2"